export const cards = [
  {
    id: '0',
    author: 'Alejandro Escamilla',
    username: '@alejandroescamilla',
    description: 'macbook laptop on a desk',
    width: 5616,
    height: 3744,
    url: 'https://unsplash.com/photos/yC-Yzbqy7PY',
    download_url: 'https://picsum.photos/id/0/5616/3744',
  },
  {
    id: '10',
    author: 'Paul Jarvis',
    username: '@pjrvs',
    description: 'Evergreen forest by the lake',
    width: 2500,
    height: 1667,
    url: 'https://unsplash.com/photos/6J--NXulQCs',
    download_url: 'https://picsum.photos/id/10/2500/1667',
  },
  {
    id: '20',
    author: 'Aleks Dorohovich',
    username: '@aleksdorohovich',
    description: 'books, pencils, laptop, and iphone on a desk',
    width: 3670,
    height: 2462,
    url: 'https://unsplash.com/photos/nJdwUHmaY8A',
    download_url: 'https://picsum.photos/id/20/3670/2462',
  },
  {
    id: '40',
    author: 'Ryan Mcguire',
    username: '@ryanmcguire',
    description: 'Cat nose',
    width: 4106,
    height: 2806,
    url: 'https://unsplash.com/photos/N-1XGL54pQg',
    download_url: 'https://picsum.photos/id/40/4106/2806',
  },
  {
    id: '179',
    author: 'Angelina Odemchuk',
    username: '@angelinaodemchuk',
    description: 'Ocean waves splashing',
    width: 2048,
    height: 1365,
    url: 'https://unsplash.com/photos/lp0IFw6YqZg',
    download_url: 'https://picsum.photos/id/179/2048/1365',
  },
];
